# .github/workflows/deploy-infra.yml
name: Deploy infra

on:
  pull_request:
    branches: [dev]
    paths: ['infrastructure/**']
  push:
    branches: [prod]
    paths: ['infrastructure/**']

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform validate

      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform apply
        if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
        run: terraform apply -auto-approve